"""Exact continuous-time generated fixture for adapter conformance.

``H-CONT-1`` is generated by the existing typed-Hawkes simulator with a small
three-type parameterization whose mark dimensions are exactly 0, 1, and 2.
All sampled marks use bounded uniform laws so the frozen generator is
byte-identical in the two supported NumPy environments.  The resulting JSON is
an exact private source fixture, not official data and not model-performance
evidence.

This module stops at the source/native boundary.  Phase-C commitments and the
shared conformance runner live in separate modules.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import math
from types import MappingProxyType
from typing import Dict, Mapping, Sequence, Tuple

import numpy as np

from heterodiff.events import EventConfiguration

from .synthetic_typed_hawkes import (
    EventTypeSpec,
    HawkesParameters,
    MarkFieldSpec,
    SimulationMetadata,
    SimulationResult,
    TypedEvent,
    simulate_typed_hawkes,
)


H_CONT_1_ID = "H-CONT-1"
H_CONT_1_SOURCE_FORMAT = "heterodiff.generated-hawkes-source.v1"
H_CONT_1_PARAMETER_ID = "heterodiff.generated-hawkes-parameters.v1"
H_CONT_1_SEED = 4
H_CONT_1_HORIZON = 5.0
H_CONT_1_MAX_EVENTS = 64
H_CONT_1_MAX_CANDIDATES = 1000
H_CONT_1_MAXIMUM_SOURCE_BYTES = 64 * 1024
H_CONT_1_MAXIMUM_EVENTS = 2048
H_CONT_1_SOURCE_SHA256 = (
    "ce4f6022bb73ab8e4025be0de65afadb111d30ea57f9e1d6b6575b685039f797"
)
H_CONT_1_SOURCE_SIZE_BYTES = 847


class GeneratedHawkesFixtureError(ValueError):
    """The generated source violates its exact fixture policy."""


def _canonical_bytes(value: object) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=True,
        allow_nan=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def _exact_nonnegative_int(value: object, *, name: str) -> int:
    if type(value) is not int:
        raise GeneratedHawkesFixtureError("{} must be an exact integer".format(name))
    if value < 0 or value > 2**53 - 1:
        raise GeneratedHawkesFixtureError("{} is outside its range".format(name))
    return value


def _exact_float_hex(value: object, *, name: str) -> float:
    if type(value) is not str or not value:
        raise GeneratedHawkesFixtureError(
            "{} must be a canonical float.hex string".format(name)
        )
    try:
        parsed = float.fromhex(value)
    except ValueError as exc:
        raise GeneratedHawkesFixtureError(
            "{} must be a canonical float.hex string".format(name)
        ) from exc
    if not math.isfinite(parsed):
        raise GeneratedHawkesFixtureError("{} must be finite".format(name))
    normalized = 0.0 if parsed == 0.0 else parsed
    if normalized.hex().lower() != value:
        raise GeneratedHawkesFixtureError("{} is not canonical".format(name))
    return normalized


def _object_without_duplicates(pairs: Sequence[Tuple[str, object]]) -> Dict[str, object]:
    result: Dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise GeneratedHawkesFixtureError(
                "generated Hawkes JSON contains a duplicate object key"
            )
        result[key] = value
    return result


def _exact_keys(value: object, keys: Sequence[str], *, name: str) -> Mapping[str, object]:
    if type(value) is not dict:
        raise GeneratedHawkesFixtureError("{} must be an exact object".format(name))
    expected = set(keys)
    observed = set(value)
    if observed != expected:
        raise GeneratedHawkesFixtureError(
            "{} keys differ: missing={}, extra={}".format(
                name, sorted(expected - observed), sorted(observed - expected)
            )
        )
    return value


def h_cont_1_parameters() -> HawkesParameters:
    """Return a fresh exact 0/1/2-dimensional Hawkes parameter object."""

    event_types = (
        EventTypeSpec(0, "pulse", (), ()),
        EventTypeSpec(
            1,
            "signal",
            (
                MarkFieldSpec(
                    "amplitude",
                    (-1.0, 1.0),
                    "uniform",
                    (("low", -1.0), ("high", 1.0)),
                ),
            ),
            (0.2,),
        ),
        EventTypeSpec(
            2,
            "context",
            (
                MarkFieldSpec(
                    "confidence",
                    (0.0, 1.0),
                    "uniform",
                    (("low", 0.0), ("high", 1.0)),
                ),
                MarkFieldSpec(
                    "offset",
                    (-2.0, 2.0),
                    "uniform",
                    (("low", -2.0), ("high", 2.0)),
                ),
            ),
            (0.1, -0.1),
        ),
    )
    return HawkesParameters(
        event_types=event_types,
        baseline=np.asarray((0.8, 0.7, 0.6), dtype=np.float64),
        excitation=np.asarray(
            (
                (0.05, 0.02, 0.01),
                (0.02, 0.05, 0.02),
                (0.01, 0.02, 0.05),
            ),
            dtype=np.float64,
        ),
        decay=np.ones((3, 3), dtype=np.float64),
    )


def _event_payload(event: TypedEvent) -> Mapping[str, object]:
    return {
        "event_type": event.event_type,
        "marks": [float(value).hex().lower() for value in event.mark],
        "time": event.time.hex().lower(),
        "type_name": event.type_name,
    }


def _metadata_payload(metadata: SimulationMetadata) -> Mapping[str, object]:
    return {
        "candidate_count": metadata.candidate_count,
        "horizon": metadata.horizon.hex().lower(),
        "max_candidates": H_CONT_1_MAX_CANDIDATES,
        "max_events": metadata.max_events,
        "parameter_id": H_CONT_1_PARAMETER_ID,
        "realized_event_counts": list(metadata.realized_event_counts),
        "seed": metadata.seed,
        "terminated_by": metadata.terminated_by,
    }


def serialize_generated_hawkes_source(result: SimulationResult) -> bytes:
    """Serialize one exact result using only canonical JSON and float hex."""

    if type(result) is not SimulationResult:
        raise TypeError("result must be an exact SimulationResult")
    return _canonical_bytes(
        {
            "events": [_event_payload(event) for event in result.events],
            "format": H_CONT_1_SOURCE_FORMAT,
            "metadata": _metadata_payload(result.metadata),
        }
    )


def generate_h_cont_1_source() -> bytes:
    """Regenerate the exact fixture through the existing Hawkes simulator."""

    result = simulate_typed_hawkes(
        seed=H_CONT_1_SEED,
        horizon=H_CONT_1_HORIZON,
        max_events=H_CONT_1_MAX_EVENTS,
        parameters=h_cont_1_parameters(),
        max_candidates=H_CONT_1_MAX_CANDIDATES,
    )
    return serialize_generated_hawkes_source(result)


H_CONT_1_BYTES = generate_h_cont_1_source()


def _parse_event(value: object, *, index: int, parameters: HawkesParameters) -> TypedEvent:
    record = _exact_keys(
        value,
        ("event_type", "marks", "time", "type_name"),
        name="event[{}]".format(index),
    )
    event_type = _exact_nonnegative_int(
        record["event_type"], name="event_type"
    )
    if event_type >= parameters.num_types:
        raise GeneratedHawkesFixtureError("event uses an unknown type")
    type_spec = parameters.event_types[event_type]
    if type(record["type_name"]) is not str or record["type_name"] != type_spec.name:
        raise GeneratedHawkesFixtureError("event type_name disagrees with event_type")
    raw_marks = record["marks"]
    if type(raw_marks) is not list:
        raise GeneratedHawkesFixtureError("event marks must be an exact array")
    if len(raw_marks) != type_spec.mark_dimension:
        raise GeneratedHawkesFixtureError("event mark dimension disagrees with schema")
    marks = np.asarray(
        [
            _exact_float_hex(item, name="event mark")
            for item in raw_marks
        ],
        dtype=np.float64,
    )
    parameters.validate_mark(event_type, marks)
    return TypedEvent(
        _exact_float_hex(record["time"], name="event time"),
        event_type,
        type_spec.name,
        marks,
    )


def parse_generated_hawkes_source(
    source_bytes: bytes,
    *,
    maximum_source_bytes: int = H_CONT_1_MAXIMUM_SOURCE_BYTES,
    maximum_events: int = H_CONT_1_MAXIMUM_EVENTS,
) -> SimulationResult:
    """Parse strict canonical generated-Hawkes JSON into native simulator types."""

    if type(source_bytes) is not bytes:
        raise TypeError("source_bytes must be exact immutable bytes")
    for value, name in (
        (maximum_source_bytes, "maximum_source_bytes"),
        (maximum_events, "maximum_events"),
    ):
        if type(value) is not int:
            raise TypeError("{} must be an exact integer".format(name))
        if value <= 0:
            raise ValueError("{} must be positive".format(name))
    if len(source_bytes) > maximum_source_bytes:
        raise GeneratedHawkesFixtureError("source byte ceiling was exceeded")
    try:
        text = source_bytes.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise GeneratedHawkesFixtureError("source must be strict UTF-8") from exc
    if text.startswith("\ufeff") or "\r" in text or "\n" in text:
        raise GeneratedHawkesFixtureError(
            "source must be single-line UTF-8 without BOM or newline"
        )
    try:
        payload = json.loads(text, object_pairs_hook=_object_without_duplicates)
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise GeneratedHawkesFixtureError("source is not valid JSON") from exc
    if _canonical_bytes(payload) != source_bytes:
        raise GeneratedHawkesFixtureError("source is not exact canonical JSON")
    root = _exact_keys(
        payload, ("events", "format", "metadata"), name="source"
    )
    if root["format"] != H_CONT_1_SOURCE_FORMAT:
        raise GeneratedHawkesFixtureError("source format differs")
    metadata_record = _exact_keys(
        root["metadata"],
        (
            "candidate_count",
            "horizon",
            "max_candidates",
            "max_events",
            "parameter_id",
            "realized_event_counts",
            "seed",
            "terminated_by",
        ),
        name="metadata",
    )
    if metadata_record["parameter_id"] != H_CONT_1_PARAMETER_ID:
        raise GeneratedHawkesFixtureError("parameter identity differs")
    if metadata_record["max_candidates"] != H_CONT_1_MAX_CANDIDATES:
        raise GeneratedHawkesFixtureError("max_candidates differs")
    events_record = root["events"]
    if type(events_record) is not list:
        raise GeneratedHawkesFixtureError("events must be an exact array")
    if len(events_record) > maximum_events:
        raise GeneratedHawkesFixtureError("event-count ceiling was exceeded")
    parameters = h_cont_1_parameters()
    events = tuple(
        _parse_event(value, index=index, parameters=parameters)
        for index, value in enumerate(events_record)
    )
    raw_counts = metadata_record["realized_event_counts"]
    if type(raw_counts) is not list or len(raw_counts) != parameters.num_types:
        raise GeneratedHawkesFixtureError(
            "realized_event_counts must cover every type"
        )
    counts = tuple(
        _exact_nonnegative_int(value, name="realized event count")
        for value in raw_counts
    )
    terminated_by = metadata_record["terminated_by"]
    if type(terminated_by) is not str:
        raise GeneratedHawkesFixtureError("terminated_by must be an exact string")
    metadata = SimulationMetadata(
        parameters=parameters,
        seed=_exact_nonnegative_int(metadata_record["seed"], name="seed"),
        horizon=_exact_float_hex(metadata_record["horizon"], name="horizon"),
        max_events=_exact_nonnegative_int(
            metadata_record["max_events"], name="max_events"
        ),
        candidate_count=_exact_nonnegative_int(
            metadata_record["candidate_count"], name="candidate_count"
        ),
        realized_event_counts=counts,
        terminated_by=terminated_by,
    )
    try:
        return SimulationResult(events, metadata)
    except (TypeError, ValueError) as exc:
        raise GeneratedHawkesFixtureError(
            "source violates generated-Hawkes semantics"
        ) from exc


def _parameter_payload(parameters: HawkesParameters) -> Mapping[str, object]:
    return {
        "baseline": [float(value).hex().lower() for value in parameters.baseline],
        "decay": [
            [float(value).hex().lower() for value in row]
            for row in parameters.decay
        ],
        "event_types": [
            {
                "excitation_weights": [
                    float(value).hex().lower()
                    for value in event_type.excitation_weights
                ],
                "fields": [
                    {
                        "distribution": field.distribution,
                        "name": field.name,
                        "parameters": [
                            [name, float(value).hex().lower()]
                            for name, value in field.parameters
                        ],
                        "support": [
                            float(value).hex().lower()
                            for value in field.support
                        ],
                    }
                    for field in event_type.fields
                ],
                "name": event_type.name,
                "type_id": event_type.type_id,
            }
            for event_type in parameters.event_types
        ],
        "excitation": [
            [float(value).hex().lower() for value in row]
            for row in parameters.excitation
        ],
        "mark_log_strength_clip": (
            parameters.mark_log_strength_clip.hex().lower()
        ),
        "parameter_id": H_CONT_1_PARAMETER_ID,
    }


@dataclass(frozen=True)
class GeneratedHawkesFixture:
    """Validated exact source plus its native and private semantic views."""

    source_bytes: bytes
    simulation: SimulationResult
    configuration: EventConfiguration
    source_sha256: str
    semantic_payload_bytes: bytes
    evaluation_parameter_bytes: bytes
    inventory_items: Tuple[Tuple[str, bytes], ...]
    private_event_payloads: Mapping[str, bytes]

    def __post_init__(self) -> None:
        if type(self.source_bytes) is not bytes:
            raise TypeError("source_bytes must be exact bytes")
        if type(self.simulation) is not SimulationResult:
            raise TypeError("simulation must be an exact SimulationResult")
        if type(self.configuration) is not EventConfiguration:
            raise TypeError("configuration must be an exact EventConfiguration")
        expected_digest = hashlib.sha256(self.source_bytes).hexdigest()
        if self.source_sha256 != expected_digest:
            raise ValueError("source_sha256 disagrees with source_bytes")
        for name in ("semantic_payload_bytes", "evaluation_parameter_bytes"):
            if type(getattr(self, name)) is not bytes or not getattr(self, name):
                raise TypeError("{} must be nonempty exact bytes".format(name))
        if type(self.inventory_items) is not tuple or not self.inventory_items:
            raise TypeError("inventory_items must be a nonempty exact tuple")
        keys = []
        items = []
        for value in self.inventory_items:
            if type(value) is not tuple or len(value) != 2:
                raise TypeError("inventory entries must be exact key/bytes tuples")
            key, raw = value
            if type(key) is not str or type(raw) is not bytes or not raw:
                raise TypeError("inventory entries must contain exact text and bytes")
            keys.append(key)
            items.append((key, raw))
        if keys != sorted(set(keys)):
            raise ValueError("inventory item keys must be sorted and unique")
        if type(self.private_event_payloads) is not MappingProxyType:
            raise TypeError("private_event_payloads must be a mapping proxy")
        if set(self.private_event_payloads) != {
            "event.{:04d}".format(index)
            for index in range(len(self.configuration.events))
        }:
            raise ValueError("private event payloads do not cover every occurrence")


def build_h_cont_1(
    *,
    sample_id: str = H_CONT_1_ID,
    group_id: str = "generated-process-group-1",
) -> GeneratedHawkesFixture:
    """Build the exact digest-locked H-CONT-1 native fixture."""

    if type(sample_id) is not str or not sample_id:
        raise TypeError("sample_id must be nonempty exact text")
    if type(group_id) is not str or not group_id:
        raise TypeError("group_id must be nonempty exact text")
    if (
        len(H_CONT_1_BYTES) != H_CONT_1_SOURCE_SIZE_BYTES
        or hashlib.sha256(H_CONT_1_BYTES).hexdigest() != H_CONT_1_SOURCE_SHA256
    ):
        raise RuntimeError("H-CONT-1 generator changed its frozen source identity")
    simulation = parse_generated_hawkes_source(H_CONT_1_BYTES)
    configuration = simulation.to_configuration(
        sample_id=sample_id, group_id=group_id
    )
    event_payloads = tuple(_event_payload(event) for event in simulation.events)
    semantic_bytes = _canonical_bytes(
        {
            "events": list(event_payloads),
            "format": "heterodiff.generated-hawkes-semantic-record.v1",
        }
    )
    parameter_bytes = _canonical_bytes(_parameter_payload(simulation.metadata.parameters))
    metadata_bytes = _canonical_bytes(_metadata_payload(simulation.metadata))
    inventory_items = tuple(
        sorted(
            (("metadata", metadata_bytes),)
            + tuple(
                ("event.{:04d}".format(index), _canonical_bytes(payload))
                for index, payload in enumerate(event_payloads)
            )
        )
    )
    private_payloads = MappingProxyType(
        {
            "event.{:04d}".format(index): _canonical_bytes(
                {
                    "event": payload,
                    "seed": simulation.metadata.seed,
                    "source_index": index,
                }
            )
            for index, payload in enumerate(event_payloads)
        }
    )
    return GeneratedHawkesFixture(
        source_bytes=H_CONT_1_BYTES,
        simulation=simulation,
        configuration=configuration,
        source_sha256=H_CONT_1_SOURCE_SHA256,
        semantic_payload_bytes=semantic_bytes,
        evaluation_parameter_bytes=parameter_bytes,
        inventory_items=inventory_items,
        private_event_payloads=private_payloads,
    )


if (
    len(H_CONT_1_BYTES) != H_CONT_1_SOURCE_SIZE_BYTES
    or hashlib.sha256(H_CONT_1_BYTES).hexdigest() != H_CONT_1_SOURCE_SHA256
):
    raise RuntimeError("H-CONT-1 embedded generator output changed identity")


__all__ = [
    "GeneratedHawkesFixture",
    "GeneratedHawkesFixtureError",
    "H_CONT_1_BYTES",
    "H_CONT_1_HORIZON",
    "H_CONT_1_ID",
    "H_CONT_1_MAX_CANDIDATES",
    "H_CONT_1_MAX_EVENTS",
    "H_CONT_1_PARAMETER_ID",
    "H_CONT_1_SEED",
    "H_CONT_1_SOURCE_FORMAT",
    "H_CONT_1_SOURCE_SHA256",
    "H_CONT_1_SOURCE_SIZE_BYTES",
    "build_h_cont_1",
    "generate_h_cont_1_source",
    "h_cont_1_parameters",
    "parse_generated_hawkes_source",
    "serialize_generated_hawkes_source",
]
