"""Exact finite-state reference tools for typed configuration processes.

The modules in this package are intentionally independent of the neural stack.
They provide a small, enumerable oracle against which approximate simulators and
learned reverse processes can be checked.
"""

from .exact_reversal import (
    ZeroMassStateError,
    reverse_generator,
    reverse_transition_matrix,
)
from .conditional_bridge import (
    ConditionalBridge,
    ZeroEvidenceError,
    UnreachableObservationStateError,
    backward_information,
    conditional_bridge,
    doob_transform_transition,
    validate_observation_likelihood,
)
from .finite_state import (
    AtomicEvent,
    Configuration,
    ConfigurationSpace,
    GeneratorValidationError,
    ProbabilityValidationError,
    birth_generator,
    combine_generators,
    death_generator,
    generator_from_off_diagonal,
    propagate_marginal,
    replacement_generator,
    transition_matrix,
    validate_generator,
    validate_probability_vector,
)
from .immigration_death import (
    CountMoments,
    ImmigrationDeathOracle,
    UnreachableCountBridgeStateError,
)
from .gaussian_particle_bridge import (
    AssociationHypothesis,
    BrownianParticleBridgeOracle,
    GaussianMixtureMoments,
    UnreachableParticleBridgeObservationError,
)
from .regional_configuration_bridge import (
    CountVector,
    FiniteRegionBridge,
    FiniteRegionConfigurationBridgeOracle,
)
from .singular_schema import (
    TwoTypeSingularSchemaOracle,
    TypeAMark,
    TypeBMark,
)
from .unordered_association import (
    log_unordered_anchor_density,
    unordered_anchor_density,
    validate_unordered_association_inputs,
)
from .path_kl import (
    CTMCPathKLDivergence,
    ctmc_path_kl,
    information_tilt_generator,
)
from .finite_atomic_counting import (
    AtomicCountVector,
    ExplicitAtomicVector,
    ExplicitReplacementRates,
    FiniteAtomicCountingSpace,
    MAX_FINITE_ATOMIC_ATOMS,
    MAX_FINITE_ATOMIC_CAP,
    MAX_FINITE_ATOMIC_STATES,
    MAX_REALIZED_PATH_JUMPS,
    RealizedCountingPathLogLikelihood,
    capped_counting_reference,
    capped_mecke_residuals,
    capped_mecke_sums,
    counting_state_relabel_permutation,
    finite_atomic_birth_generator,
    finite_atomic_death_generator,
    finite_atomic_generator,
    finite_atomic_path_kl,
    finite_atomic_replacement_generator,
    finite_atomic_reverse_flux_residuals,
    finite_atomic_reverse_generator,
    realized_counting_path_log_likelihood,
)
from .finite_atomic_association_bridge import (
    FiniteAtomicAssociationBridgeOracle,
    PositiveFiniteAtomicObservation,
    TransitionFamily,
)
from .finite_atomic_overflow_observation import (
    FiniteAtomicObservationValue,
    OVERFLOW_OBSERVATION,
    OverflowObservation,
    PositiveFiniteAtomicOverflowObservation,
)
from .finite_atomic_reference_guide import (
    IndependentFiniteAtomicReferenceGuide,
)
from .finite_bridge_population import (
    FiniteBridgePopulation,
    equal_prior_logistic_risk_per_time,
    finite_bridge_population,
    population_equal_prior_logistic_risk,
)
from .finite_bridge_path_control import (
    FiniteBridgePathKL,
    FiniteCTMCPathSample,
    TabulatedPositivePotential,
    TiltedInitialLaw,
    TimeIndexedOccupancy,
    conditional_initial_law,
    integrate_tilted_occupancy,
    potential_tilted_generator,
    sample_tabulated_tilted_path,
    tilted_path_kl,
)

__all__ = [
    "AtomicEvent",
    "AtomicCountVector",
    "AssociationHypothesis",
    "BrownianParticleBridgeOracle",
    "ConditionalBridge",
    "CTMCPathKLDivergence",
    "Configuration",
    "ConfigurationSpace",
    "CountVector",
    "CountMoments",
    "FiniteRegionBridge",
    "FiniteRegionConfigurationBridgeOracle",
    "FiniteAtomicCountingSpace",
    "FiniteAtomicAssociationBridgeOracle",
    "FiniteAtomicObservationValue",
    "FiniteBridgePathKL",
    "FiniteBridgePopulation",
    "FiniteCTMCPathSample",
    "GeneratorValidationError",
    "GaussianMixtureMoments",
    "ImmigrationDeathOracle",
    "IndependentFiniteAtomicReferenceGuide",
    "ExplicitAtomicVector",
    "ExplicitReplacementRates",
    "MAX_FINITE_ATOMIC_ATOMS",
    "MAX_FINITE_ATOMIC_CAP",
    "MAX_FINITE_ATOMIC_STATES",
    "MAX_REALIZED_PATH_JUMPS",
    "ProbabilityValidationError",
    "PositiveFiniteAtomicObservation",
    "PositiveFiniteAtomicOverflowObservation",
    "RealizedCountingPathLogLikelihood",
    "TwoTypeSingularSchemaOracle",
    "TypeAMark",
    "TypeBMark",
    "TransitionFamily",
    "OVERFLOW_OBSERVATION",
    "OverflowObservation",
    "TabulatedPositivePotential",
    "TiltedInitialLaw",
    "TimeIndexedOccupancy",
    "ZeroEvidenceError",
    "UnreachableObservationStateError",
    "UnreachableCountBridgeStateError",
    "UnreachableParticleBridgeObservationError",
    "ZeroMassStateError",
    "birth_generator",
    "backward_information",
    "capped_counting_reference",
    "capped_mecke_residuals",
    "capped_mecke_sums",
    "combine_generators",
    "conditional_bridge",
    "conditional_initial_law",
    "counting_state_relabel_permutation",
    "ctmc_path_kl",
    "death_generator",
    "doob_transform_transition",
    "generator_from_off_diagonal",
    "finite_atomic_birth_generator",
    "finite_atomic_death_generator",
    "finite_atomic_generator",
    "finite_atomic_path_kl",
    "finite_atomic_replacement_generator",
    "finite_atomic_reverse_flux_residuals",
    "finite_atomic_reverse_generator",
    "finite_bridge_population",
    "information_tilt_generator",
    "integrate_tilted_occupancy",
    "log_unordered_anchor_density",
    "propagate_marginal",
    "population_equal_prior_logistic_risk",
    "potential_tilted_generator",
    "replacement_generator",
    "realized_counting_path_log_likelihood",
    "reverse_generator",
    "reverse_transition_matrix",
    "sample_tabulated_tilted_path",
    "tilted_path_kl",
    "transition_matrix",
    "unordered_anchor_density",
    "validate_generator",
    "validate_observation_likelihood",
    "validate_probability_vector",
    "validate_unordered_association_inputs",
    "equal_prior_logistic_risk_per_time",
]
